### ISSUE TITLE
Empty runeset causes infinite loop on startup

### ISSUE THREAD

**Issue by EricSpeidel** [Betalord/BHBot#87]
**Describe the bug**
The startup rune set check will fail and be repeated infinitely if you have no runes on your character.

**To Reproduce**
1. Take off all your runes
2. Use default settings.ini
3. Run the bot
4. After the other initial checks (ignore boss/shrine) the boss will go on to check your initial rune set, failing to detect it and keep on repeating itself.

**Expected behavior**
Detecting the absence of (minor) runes, proceeding instead of retrying looking for runes it might have missed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chromium
 - Version Latest, self-compiled, happens with the latest release as well though

**Additional context**
It is working fine when I got my runes on initially, so I don't think it's an issue with my scaling or graphics.

**Comment by EricSpeidel** [comment]
Here's a log: `2019-06-11 15:56:25,536 [main] INFO BHBotLogger - BHBot v40 build on Tue Jun 11 15:43:24 CEST 2019 started.
2019-06-11 15:56:25,550 [main] INFO BHBotLogger - GIT commit id: 49e8c5324e5ff03c70ef4e771735e89fc714e2a6  time: 2019-06-10T01:47:19+0200
2019-06-11 15:56:25,974 [main] DEBUG BHBotLogger - BHBot is running on the latest version.
2019-06-11 15:56:25,978 [main] INFO BHBotLogger - Settings loaded from file
2019-06-11 15:56:25,979 [main] INFO BHBotLogger - Character: XXXXXXXXX
2019-06-11 15:56:26,783 [main] DEBUG BHBotLogger - Reading JAR File for cues in path cues/familiars/new_format/
2019-06-11 15:56:27,090 [main] DEBUG BHBotLogger - Found 123 familiar cue(s) with new format.
2019-06-11 15:56:27,091 [main] DEBUG BHBotLogger - Found Chromium in C:\Users\Eric\AppData\Local\Chromium\Application\chrome.exe
2019-06-11 15:56:27,092 [main] DEBUG BHBotLogger - Found chromedriver in E:\Programme\BHBot\XXXXXXXX\chromedriver.exe
2019-06-11 15:56:27,092 [main] DEBUG BHBotLogger - Found screenshots in E:\Programme\BHBot\XXXXXXXX\screenshots
2019-06-11 15:56:27,093 [MainThread] INFO BHBotLogger - Driver started succesfully
2019-06-11 15:56:42,859 [MainThread] INFO BHBotLogger - Game element found. Starting to run bot..
2019-06-11 15:57:15,598 [MainThread] INFO BHBotLogger - Startup check to make sure autoShrine is initially disabled
2019-06-11 15:57:17,207 [MainThread] DEBUG BHBotLogger - Ignore Boss Disabled
2019-06-11 15:57:17,220 [MainThread] DEBUG BHBotLogger - Ignore Shrine Disabled
2019-06-11 15:57:22,139 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:28,499 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:28,499 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:28,500 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:29,308 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:35,659 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:35,660 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:35,660 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:36,467 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:42,852 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:42,853 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:42,854 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:43,673 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:50,030 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:50,030 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:50,031 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:50,859 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:57,200 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:57,200 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:57,201 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:58,034 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:58:04,402 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:58:04,403 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:58:04,403 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:58:05,205 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:58:11,582 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:58:11,583 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:58:11,584 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:58:12,402 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes`

**Comment by EricSpeidel** [comment]
Here's a log:
```
2019-06-11 15:56:25,536 [main] INFO BHBotLogger - BHBot v40 build on Tue Jun 11 15:43:24 CEST 2019 started.
2019-06-11 15:56:25,550 [main] INFO BHBotLogger - GIT commit id: 49e8c5324e5ff03c70ef4e771735e89fc714e2a6  time: 2019-06-10T01:47:19+0200
2019-06-11 15:56:25,974 [main] DEBUG BHBotLogger - BHBot is running on the latest version.
2019-06-11 15:56:25,978 [main] INFO BHBotLogger - Settings loaded from file
2019-06-11 15:56:25,979 [main] INFO BHBotLogger - Character: XXXXXXXXX
2019-06-11 15:56:26,783 [main] DEBUG BHBotLogger - Reading JAR File for cues in path cues/familiars/new_format/
2019-06-11 15:56:27,090 [main] DEBUG BHBotLogger - Found 123 familiar cue(s) with new format.
2019-06-11 15:56:27,091 [main] DEBUG BHBotLogger - Found Chromium in C:\Users\XXXXXXXXX\AppData\Local\Chromium\Application\chrome.exe
2019-06-11 15:56:27,092 [main] DEBUG BHBotLogger - Found chromedriver in E:\Programme\BHBot\XXXXXXXXX\chromedriver.exe
2019-06-11 15:56:27,092 [main] DEBUG BHBotLogger - Found screenshots in E:\Programme\BHBot\XXXXXXXXX\screenshots
2019-06-11 15:56:27,093 [MainThread] INFO BHBotLogger - Driver started succesfully
2019-06-11 15:56:42,859 [MainThread] INFO BHBotLogger - Game element found. Starting to run bot..
2019-06-11 15:57:15,598 [MainThread] INFO BHBotLogger - Startup check to make sure autoShrine is initially disabled
2019-06-11 15:57:17,207 [MainThread] DEBUG BHBotLogger - Ignore Boss Disabled
2019-06-11 15:57:17,220 [MainThread] DEBUG BHBotLogger - Ignore Shrine Disabled
2019-06-11 15:57:22,139 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:28,499 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:28,499 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:28,500 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:29,308 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:35,659 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:35,660 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:35,660 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:36,467 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:42,852 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:42,853 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:42,854 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:43,673 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:50,030 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:50,030 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:50,031 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:50,859 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:57:57,200 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:57:57,200 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:57:57,201 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:57:58,034 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:58:04,402 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:58:04,403 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:58:04,403 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:58:05,205 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes
2019-06-11 15:58:11,582 [MainThread] WARN BHBotLogger - Error: Unable to detect left minor rune!
2019-06-11 15:58:11,583 [MainThread] WARN BHBotLogger - Error: Unable to detect right minor rune!
2019-06-11 15:58:11,584 [MainThread] ERROR BHBotLogger - It was not possible to perform the equipped runes start-up check! Disabling autoRune..
2019-06-11 15:58:12,402 [MainThread] INFO BHBotLogger - Startup check to determined configured minor runes

```

**Comment by EricSpeidel** [comment]
Playing around with the code, the loop occurs because the the `oneTimeRuneCheck` variable is still false after encountering this. However, just setting it to true before continuing the oneTime checks doesn't do the trick, as it will fail loading the rune configuration once it starts the first activity. I'm not really deep into the code, so I'm probably missing a simple way of turning off autorune altogether.

**Comment by Fortigate** [comment]
Thanks for investigating it, I'll put in a fix for the `BHBot.settings.setAutoRuneDefaultFromString("");` evaluating to true

**Comment by Fortigate** [comment]
Should be fixed as of 67271ff64a38df2ef706b2e32cf416c43ce66668

**Comment by KiloChaser** [comment]
Bug is still present as of 7/7/19, latest version. Left and right rune slots are empty and the bot goes into an infinite loop.
